In [153]:
import pandas as pd
import utilities

In [154]:
df_original = pd.read_csv("jobs_linkedin_parsed.csv")
df_original.head()

,offer_id,title,company_name,city,state_code,seniority_level,job_type,job_function,industry,description,salary_min,salary_max,salary_unit,salary,searched_position,searched_location,applications
0,0,Software Engineering Graduate,Hewlett Packard Enterprise,Roseville,CA,Not Applicable,Full-time,Engineering and Information Technology,IT Services and IT Consulting,This role has been designed as ‘Hybrid’ with a...,70000.0,161700.0,year,"$70,000.00/yr - $161,700.00/yr",Software Engineer,Elk Grove,Over 200 applicants
1,1,Software Engineer,Veracity Software Inc,Sacramento,CA,Mid-Senior level,Full-time,Other,IT Services and IT Consulting,Job Title: Software EngineerLocation: Sacramen...,NaN,NaN,NaN,NaN,Software Engineer,Elk Grove,Be among the first 25 applicants
2,2,Software Engineer,Epic,Elk Grove,CA,Entry level,Full-time,Engineering and Information Technology,Software Development,Please note that this position is based on our...,NaN,NaN,NaN,NaN,Software Engineer,Elk Grove,197 applicants
3,3,Software Engineer,Epic,Sacramento,CA,Entry level,Full-time,Engineering and Information Technology,Software Development,Please note that this position is based on our...,NaN,NaN,NaN,NaN,Software Engineer,Elk Grove,190 applicants
4,4,Software Engineering Intern,Hewlett Packard Enterprise,Roseville,CA,Not Applicable,Full-time,Engineering and Information Technology,IT Services and IT Consulting,This role has been designed as ‘Hybrid’ with a...,35.0,46.0,hour,$35.00/hr - $46.00/hr,Software Engineer,Elk Grove,Over 200 applicants

# EDA

In [155]:
df = df_original.copy()

## Cleaning Dataset 

Investigating the job_type column. 
Firstly, we remove the 6 entries from Volunteer job type since they do not have a salary. 

Salaries for other categories:
Temporary wages (38 data points) have 32% missing, 37% hourly wage and 32% yearly wage

Contract (634 data points) wages are 57% missing, 34% hourly and 9% yearly

Other (18 data points) wages are 61% missing, 11% hourly and 28% yearly

Part-time (72 data points) wages are 61% missing, 11% hourly and 28% yearly

Internship (220 data points) wages are 47% missing, 36% hourly and 15% yearly

Full-time (9508 data points) wages are 33% missing, 4% hourly and 62% yearly

In [156]:
df['job_type'].unique()

array(['Full-time', 'Internship', 'Contract', 'Part-time', 'Volunteer',
       'Other', 'Temporary'], dtype=object)

In [157]:
df = df[(df['job_type']!='Volunteer')]
df

,offer_id,title,company_name,city,state_code,seniority_level,job_type,job_function,industry,description,salary_min,salary_max,salary_unit,salary,searched_position,searched_location,applications
0,0,Software Engineering Graduate,Hewlett Packard Enterprise,Roseville,CA,Not Applicable,Full-time,Engineering and Information Technology,IT Services and IT Consulting,This role has been designed as ‘Hybrid’ with a...,70000.0,161700.0,year,"$70,000.00/yr - $161,700.00/yr",Software Engineer,Elk Grove,Over 200 applicants
1,1,Software Engineer,Veracity Software Inc,Sacramento,CA,Mid-Senior level,Full-time,Other,IT Services and IT Consulting,Job Title: Software EngineerLocation: Sacramen...,NaN,NaN,NaN,NaN,Software Engineer,Elk Grove,Be among the first 25 applicants
2,2,Software Engineer,Epic,Elk Grove,CA,Entry level,Full-time,Engineering and Information Technology,Software Development,Please note that this position is based on our...,NaN,NaN,NaN,NaN,Software Engineer,Elk Grove,197 applicants
3,3,Software Engineer,Epic,Sacramento,CA,Entry level,Full-time,Engineering and Information Technology,Software Development,Please note that this position is based on our...,NaN,NaN,NaN,NaN,Software Engineer,Elk Grove,190 applicants
4,4,Software Engineering Intern,Hewlett Packard Enterprise,Roseville,CA,Not Applicable,Full-time,Engineering and Information Technology,IT Services and IT Consulting,This role has been designed as ‘Hybrid’ with a...,35.0,46.0,hour,$35.00/hr - $46.00/hr,Software Engineer,Elk Grove,Over 200 applicants
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10491,10491,Senior Engineer - Structural,"Global Technical Talent, an Inc. 5000 Company",Pomona,CA,Entry level,Contract,Engineering and Information Technology,Utilities,Primary Job Title:Senior Engineer - Structural...,NaN,NaN,NaN,NaN,Civil Engineer,Colton,Be among the first 25 applicants
10492,10492,Senior Engineer V,"Global Technical Talent, an Inc. 5000 Company",Pomona,CA,Entry level,Contract,Engineering and Information Technology,Utilities,Senior Engineer VAlternate Job Titles:Civil En...,NaN,NaN,NaN,NaN,Civil Engineer,Colton,Be among the first 25 applicants
10493,10493,Construction Survey Project Manager – Californ...,"David Evans and Associates, Inc.",Apple Valley,CA,Mid-Senior level,Full-time,Project Management and Information Technology,Civil Engineering,Construction Survey Project Manager – Californ...,105000.0,175000.0,year,"$105,000.00/yr - $175,000.00/yr",Civil Engineer,Victorville,Be among the first 25 applicants
10494,10494,Substation Project Engineer *,HDR,Claremont,CA,Mid-Senior level,Full-time,"Management, Consulting, and Engineering","Oil and Gas, Utilities, and Appliances, Electr...","At HDR, our employee-owners are fully engaged ...",NaN,NaN,NaN,NaN,Chemical Engineer,Colton,Be among the first 25 applicants
10495,10495,"Environmental Health, Safety & Security Specia...",McKesson,Chino,CA,Mid-Senior level,Full-time,Management and Manufacturing,Hospitals and Health Care,"McKesson is an impact-driven, Fortune 10 compa...",94400.0,157400.0,year,"$94,400.00/yr - $157,400.00/yr",Environmental Engineer,Colton,Be among the first 25 applicants

In [158]:
# df_filtered = df[(df['job_type']=='Part-time')]
# df_filtered

## Formatting Salary

In [159]:
# Converting monthly salary to yearly salary

from utilities import format_salary

# Find rows paid monthly
monthly = df["salary_unit"].str.contains("month", case=False, na=False)
# df.loc[monthly, ["salary_min", "salary_max"]].head(20)

# Checking for NaNs (exist in float64)
df.loc[monthly, ["salary_min", "salary_max"]].isna().any(axis=1).sum()
df.loc[monthly, ["salary_min", "salary_max"]].applymap(lambda x: (repr(x), type(x)))

C:\Users\bucky\AppData\Local\Temp\ipykernel_3512\103879051.py:11: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.loc[monthly, ["salary_min", "salary_max"]].applymap(lambda x: (repr(x), type(x)))

                      salary_min                  salary_max
22     (6323.0, <class 'float'>)  (10536.0, <class 'float'>)
24     (8625.0, <class 'float'>)  (11557.0, <class 'float'>)
26     (6513.0, <class 'float'>)  (10537.0, <class 'float'>)
52     (8625.0, <class 'float'>)  (11557.0, <class 'float'>)
162    (8625.0, <class 'float'>)  (11557.0, <class 'float'>)
...                          ...                         ...
10112  (6488.0, <class 'float'>)  (12152.0, <class 'float'>)
10113  (6488.0, <class 'float'>)  (12152.0, <class 'float'>)
10125  (6488.0, <class 'float'>)  (12152.0, <class 'float'>)
10154  (7284.0, <class 'float'>)  (10611.0, <class 'float'>)
10241  (1500.0, <class 'float'>)   (5000.0, <class 'float'>)

[77 rows x 2 columns]

In [160]:
# Update salary with vectorial operation
df.loc[monthly, "salary_min"] = (df.loc[monthly, "salary_min"] * 12).round(2)
df.loc[monthly, "salary_max"] = (df.loc[monthly, "salary_max"] * 12).round(2)

# Update salary  
df.loc[monthly, "salary"] = (
    df.loc[monthly].apply(lambda row: format_salary(row["salary_min"], row["salary_max"], "yr"), axis=1)
)

# Update salary_unit
df.loc[monthly, "salary_unit"] = "year"

In [161]:
valid = monthly & df["salary_min"].notna() & df["salary_max"].notna()
bad_rows = df.loc[monthly & ~valid, ["salary_min","salary_max","salary"]]
print(bad_rows)
len(bad_rows)

Empty DataFrame
Columns: [salary_min, salary_max, salary]
Index: []

0

In [162]:
# Converting hourly salary to yearly salary

# First, detect outliers that are already in yearly format

is_hourly = df["salary_unit"].str.contains("hour", case=False, na=False)
is_outlier = (is_hourly & (df["salary_min"]>1000))
is_part_time = df["job_type"].str.contains("Part-time", case=False, na=False)

# Find rows paid hourly, but filter out the part-time jobs and assume 20
hourly_outliers = (is_hourly & is_outlier)
hourly_rest = (is_hourly & ~is_outlier)
hourly_part = (is_hourly & is_part_time & ~is_outlier)
hourly_full = (is_hourly & ~is_part_time & ~is_outlier)

In [163]:
# Directly handle outliers
# Update salary  
df.loc[hourly_outliers, "salary"] = (
    df.loc[hourly_outliers].apply(lambda row: format_salary(row["salary_min"], row["salary_max"], "yr"), axis=1)
)
# Update salary_unit
df.loc[hourly_outliers, "salary_unit"] = "year"

In [164]:

# Checking for NaNs (exist in float64)
df.loc[hourly_part, ["salary_min", "salary_max"]].isna().any(axis=1).sum()
df.loc[hourly_part, ["salary_min", "salary_max"]].applymap(lambda x: (repr(x), type(x)))

C:\Users\bucky\AppData\Local\Temp\ipykernel_3512\1430106037.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.loc[hourly_part, ["salary_min", "salary_max"]].applymap(lambda x: (repr(x), type(x)))

                     salary_min                salary_max
264    (28.99, <class 'float'>)  (34.03, <class 'float'>)
1893    (30.0, <class 'float'>)   (40.0, <class 'float'>)
2416    (20.0, <class 'float'>)   (25.0, <class 'float'>)
2473    (30.0, <class 'float'>)   (40.0, <class 'float'>)
4007   (22.73, <class 'float'>)  (23.85, <class 'float'>)
4271   (140.0, <class 'float'>)  (140.0, <class 'float'>)
4280    (85.0, <class 'float'>)   (85.0, <class 'float'>)
5096    (30.0, <class 'float'>)   (60.0, <class 'float'>)
6081    (25.0, <class 'float'>)   (28.0, <class 'float'>)
6278    (19.0, <class 'float'>)   (28.0, <class 'float'>)
6359    (80.0, <class 'float'>)   (90.0, <class 'float'>)
6521   (42.78, <class 'float'>)  (53.42, <class 'float'>)
6927   (51.77, <class 'float'>)  (98.13, <class 'float'>)
7935    (20.0, <class 'float'>)   (28.0, <class 'float'>)
9239    (21.0, <class 'float'>)  (24.15, <class 'float'>)
9720    (55.0, <class 'float'>)   (60.0, <class 'float'>)
10104   (17.5, <class 'float'>)   (20.3, <class 'float'>)
10451  (70.93, <class 'float'>)  (90.52, <class 'float'>)

In [167]:
# Update salary with vectorial operation
df.loc[hourly_part, "salary_min"] = (df.loc[hourly_part, "salary_min"] * 20 * 12).round(2)
df.loc[hourly_part, "salary_max"] = (df.loc[hourly_part, "salary_min"] * 20 * 12).round(2)

df.loc[hourly_full, "salary_min"] = (df.loc[hourly_full, "salary_max"] * 40 * 12).round(2)
df.loc[hourly_full, "salary_max"] = (df.loc[hourly_full, "salary_max"] * 40 * 12).round(2)


# Update salary  
df.loc[hourly_rest, "salary"] = (
    df.loc[hourly_rest].apply(lambda row: format_salary(row["salary_min"], row["salary_max"], "yr"), axis=1)
)

# Update salary_unit
df.loc[hourly_rest, "salary_unit"] = "year"

In [166]:
df

,offer_id,title,company_name,city,state_code,seniority_level,job_type,job_function,industry,description,salary_min,salary_max,salary_unit,salary,searched_position,searched_location,applications
0,0,Software Engineering Graduate,Hewlett Packard Enterprise,Roseville,CA,Not Applicable,Full-time,Engineering and Information Technology,IT Services and IT Consulting,This role has been designed as ‘Hybrid’ with a...,70000.0,161700.0,year,"$70,000.00/yr - $161,700.00/yr",Software Engineer,Elk Grove,Over 200 applicants
1,1,Software Engineer,Veracity Software Inc,Sacramento,CA,Mid-Senior level,Full-time,Other,IT Services and IT Consulting,Job Title: Software EngineerLocation: Sacramen...,NaN,NaN,NaN,NaN,Software Engineer,Elk Grove,Be among the first 25 applicants
2,2,Software Engineer,Epic,Elk Grove,CA,Entry level,Full-time,Engineering and Information Technology,Software Development,Please note that this position is based on our...,NaN,NaN,NaN,NaN,Software Engineer,Elk Grove,197 applicants
3,3,Software Engineer,Epic,Sacramento,CA,Entry level,Full-time,Engineering and Information Technology,Software Development,Please note that this position is based on our...,NaN,NaN,NaN,NaN,Software Engineer,Elk Grove,190 applicants
4,4,Software Engineering Intern,Hewlett Packard Enterprise,Roseville,CA,Not Applicable,Full-time,Engineering and Information Technology,IT Services and IT Consulting,This role has been designed as ‘Hybrid’ with a...,22080.0,22080.0,hour,"$22,080.00/yr - $22,080.00/yr",Software Engineer,Elk Grove,Over 200 applicants
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10491,10491,Senior Engineer - Structural,"Global Technical Talent, an Inc. 5000 Company",Pomona,CA,Entry level,Contract,Engineering and Information Technology,Utilities,Primary Job Title:Senior Engineer - Structural...,NaN,NaN,NaN,NaN,Civil Engineer,Colton,Be among the first 25 applicants
10492,10492,Senior Engineer V,"Global Technical Talent, an Inc. 5000 Company",Pomona,CA,Entry level,Contract,Engineering and Information Technology,Utilities,Senior Engineer VAlternate Job Titles:Civil En...,NaN,NaN,NaN,NaN,Civil Engineer,Colton,Be among the first 25 applicants
10493,10493,Construction Survey Project Manager – Californ...,"David Evans and Associates, Inc.",Apple Valley,CA,Mid-Senior level,Full-time,Project Management and Information Technology,Civil Engineering,Construction Survey Project Manager – Californ...,105000.0,175000.0,year,"$105,000.00/yr - $175,000.00/yr",Civil Engineer,Victorville,Be among the first 25 applicants
10494,10494,Substation Project Engineer *,HDR,Claremont,CA,Mid-Senior level,Full-time,"Management, Consulting, and Engineering","Oil and Gas, Utilities, and Appliances, Electr...","At HDR, our employee-owners are fully engaged ...",NaN,NaN,NaN,NaN,Chemical Engineer,Colton,Be among the first 25 applicants
10495,10495,"Environmental Health, Safety & Security Specia...",McKesson,Chino,CA,Mid-Senior level,Full-time,Management and Manufacturing,Hospitals and Health Care,"McKesson is an impact-driven, Fortune 10 compa...",94400.0,157400.0,year,"$94,400.00/yr - $157,400.00/yr",Environmental Engineer,Colton,Be among the first 25 applicants

In [ ]:
# TODO: Add a column for is_converted
# TODO: Change the functions in utilities to reflect current usage and modularize